/*------------------------------SEQUENCE AREA-------------------------------------------*/
/*예약 번호 시퀀스*/
CREATE SEQUENCE SEQ_RE
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/*유저 번호 시퀀스*/
CREATE SEQUENCE SEQ_USER
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/*운전자 번호 시퀀스*/
CREATE SEQUENCE SEQ_DR
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/*------------------------------TABLE AREA-------------------------------------------*/

/*차량 종류 테이블*/
CREATE TABLE CAR(
	C_CODE NUMBER PRIMARY KEY,
	C_NAME VARCHAR2(30) NOT NULL,
	MAX_WEIGHT NUMBER NOT NULL
);

/* 운전자 테이블*/
CREATE TABLE DRIVER(
	D_CODE NUMBER PRIMARY KEY,
	D_NAME VARCHAR2(30) NOT NULL,
	D_CAR VARCHAR2(30),
	D_PHONE VARCHAR2(50) NOT NULL,
	D_BIRTH DATE,
	CONSTRAINT FK_DRIVER_CAR FOREIGN KEY(D_CAR) REFERENCES CAR(C_CODE)
);

/*유저 테이블*/
CREATE TABLE USER(
    U_CODE NUMBER PRIMARY KEY,
    U_NAME VARCHAR2(30) NOT NULL,
    U_BIRTH DATE NOT NULL,
    U_CAR NUMBER,
    U_PHONE VARCHAR2(60) NOT NULL,
    U_EMAIL VARCHAR2(60) NOT NULL,
    U_ADDRESS VARCHAR2(300) NOT NULL
);

/*예약 테이블*/
CREATE TABLE RESERVATION(
    R_CODE NUMBER PRIMARY KEY,
    R_DATE DATE NOT NULL,
    CO_DATE DATE NOT NULL,
    ST_PLACE VARCHAR2(300) NOT NULL,
    EN_PLACE VARCHAR2(300) NOT NULL,
    U_CODE NUMBER,
    PRICE NUMBER NOT NULL,
    CONSTRAINT FK_USER_RESER FOREIGN KEY(U_CODE) REFERENCES USER(U_CODE)
);


/*------------------------------INSERT AREA-------------------------------------------*/