DROP TABLE MEMBER CASCADE CONSTRAINTS;
DROP TABLE DRIVER CASCADE CONSTRAINTS;
DROP TABLE NOTICE CASCADE CONSTRAINTS;
DROP TABLE ADDRESS CASCADE CONSTRAINTS;
DROP TABLE CALCULATE CASCADE CONSTRAINTS;
DROP TABLE PAYMENT CASCADE CONSTRAINTS;
DROP TABLE RESERVATION CASCADE CONSTRAINTS;
DROP TABLE CHATROOM CASCADE CONSTRAINTS;
DROP TABLE CHATMESSAGE CASCADE CONSTRAINTS;

DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_DNO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_ANO;
DROP SEQUENCE SEQ_RNO;
DROP SEQUENCE SEQ_PNO;
DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_CRNO;
DROP SEQUENCE SEQ_CMNO;


-- MEMBER
CREATE TABLE MEMBER(
    M_NO VARCHAR2(50) /* 회원번호 */,       
    M_ID VARCHAR2(50) /* 회원 ID(이메일) */,                 
    PWD CHAR(60) /* 비밀번호 */,
    NAME VARCHAR2(50) /* 이름 */,
    PHONE VARCHAR2(14) /* 휴대폰번호 */,
    M_SORT VARCHAR2(9)/* 회원구분(관리자, 일반, 사업자) */,
    M_STATUS CHAR(6) /* 회원상태(정상, 휴면, 탈퇴) */,
    SIGNUP_TYPE VARCHAR2(12) /* 가입타입(용달이, 네이버, 카카오, 페이스북) */,
    PUSH_ENABLED CHAR(1) /* 푸시 알림 설정(Y, N) */,
    ENROLLDATE DATE DEFAULT SYSDATE /* 가입일 */
);

ALTER TABLE MEMBER ADD CONSTRAINT M_PK_NO PRIMARY KEY (M_NO);
ALTER TABLE MEMBER ADD CONSTRAINT M_UQ_ID UNIQUE (M_ID);
ALTER TABLE MEMBER ADD CONSTRAINT M_CK_SORT CHECK (M_SORT IN ('관리자', '일반', '사업자'));
ALTER TABLE MEMBER ADD CONSTRAINT M_CK_STATUS CHECK (M_STATUS IN ('정상', '휴면', '탈퇴'));
ALTER TABLE MEMBER ADD CONSTRAINT M_CK_TYPE CHECK (SIGNUP_TYPE IN ('용달이', '네이버', '카카오', '페이스북'));
ALTER TABLE MEMBER ADD CONSTRAINT M_CK_PUSH CHECK (PUSH_ENABLED IN ('Y', 'N'));

ALTER TABLE MEMBER MODIFY M_ID CONSTRAINT M_NN_ID NOT NULL;
ALTER TABLE MEMBER MODIFY NAME CONSTRAINT M_NN_NAME NOT NULL;
ALTER TABLE MEMBER MODIFY M_SORT CONSTRAINT M_NN_SORT NOT NULL;
ALTER TABLE MEMBER MODIFY M_STATUS CONSTRAINT M_NN_STATUS NOT NULL;
ALTER TABLE MEMBER MODIFY SIGNUP_TYPE CONSTRAINT M_NN_TYPE NOT NULL;
ALTER TABLE MEMBER MODIFY ENROLLDATE CONSTRAINT M_NN_ENROLLDATE NOT NULL;

COMMENT ON COLUMN MEMBER.M_NO IS '회원번호';
COMMENT ON COLUMN MEMBER.M_ID IS '회원 ID(이메일)';
COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NAME IS '이름';
COMMENT ON COLUMN MEMBER.PHONE IS '휴대폰번호';
COMMENT ON COLUMN MEMBER.M_SORT IS '회원구분(관리자, 일반, 사업자)';
COMMENT ON COLUMN MEMBER.M_STATUS IS '회원상태(정상, 휴면, 탈퇴)';
COMMENT ON COLUMN MEMBER.SIGNUP_TYPE IS '가입타입(용달이, 네이버, 카카오, 페이스북)';
COMMENT ON COLUMN MEMBER.PUSH_ENABLED IS '푸시 알림 설정(Y, N)';
COMMENT ON COLUMN MEMBER.ENROLLDATE IS '가입일';


-- DRIVER
CREATE TABLE DRIVER(
    D_NO VARCHAR2(50) /* 기사(사업자) 번호 */,
    D_M_NO VARCHAR2(50) /* 회원번호(FK) */,
    CAPACITY NUMBER(2,1) /* 차량 톤수 */,
    TYPE VARCHAR2(17) /* 차종 */ ,
    CAR_NO VARCHAR2(17) /* 차량번호 */,
    ID_IMG_ORIGIN VARCHAR2(300) /* 증명사진 원명*/,
    ID_IMG_RENAME VARCHAR2(300) /* 증명사진 가명*/,
    REGCARD_IMG_ORIGIN VARCHAR2(300) /* 차량등록증 원명*/,
    REGCARD_IMG_RENAME VARCHAR2(300) /* 차량등록증 가명*/
);

ALTER TABLE DRIVER ADD CONSTRAINT D_PK_NO PRIMARY KEY (D_NO);
ALTER TABLE DRIVER ADD CONSTRAINT D_M_FK_NO FOREIGN KEY (D_M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE;
ALTER TABLE DRIVER MODIFY D_M_NO CONSTRAINT D_M_NN_NO NOT NULL;
ALTER TABLE DRIVER MODIFY CAPACITY CONSTRAINT D_NN_CAPACITY NOT NULL;
ALTER TABLE DRIVER MODIFY TYPE CONSTRAINT D_NN_TYPE NOT NULL;
ALTER TABLE DRIVER MODIFY CAR_NO CONSTRAINT D_NN_CAR_NO NOT NULL;
ALTER TABLE DRIVER MODIFY ID_IMG_ORIGIN CONSTRAINT D_NN_ID_IMG_ORIGIN NOT NULL;
ALTER TABLE DRIVER MODIFY ID_IMG_RENAME CONSTRAINT D_NN_ID_IMG_RENAME NOT NULL;
ALTER TABLE DRIVER MODIFY REGCARD_IMG_ORIGIN CONSTRAINT D_NN_REGCARD_IMG_ORIGIN NOT NULL;
ALTER TABLE DRIVER MODIFY REGCARD_IMG_RENAME CONSTRAINT D_NN_REGCARD_IMG_RENAME NOT NULL;

COMMENT ON COLUMN DRIVER.D_NO IS '기사(사업자) 번호';
COMMENT ON COLUMN DRIVER.D_M_NO IS '회원번호(FK)';
COMMENT ON COLUMN DRIVER.CAPACITY IS '차량 톤수';
COMMENT ON COLUMN DRIVER.TYPE IS '차종';
COMMENT ON COLUMN DRIVER.CAR_NO IS '차량번호';
COMMENT ON COLUMN DRIVER.ID_IMG_ORIGIN IS '증명사진 원명';
COMMENT ON COLUMN DRIVER.ID_IMG_RENAME IS '증명사진 가명';
COMMENT ON COLUMN DRIVER.REGCARD_IMG_ORIGIN IS '차량등록증 원명';
COMMENT ON COLUMN DRIVER.REGCARD_IMG_RENAME IS '차량등록증 가명';


-- NOTICE
CREATE TABLE NOTICE(
    N_NO VARCHAR2(50) /* 번호 */,
    N_TITLE VARCHAR2(100) /* 제목 */,
    N_WRITER VARCHAR2(50) /* 작성자 */,
    N_CONTENT VARCHAR2(2100) /* 내용 */,
    N_IMG_ORIGIN VARCHAR2(300) /* 첨부파일 원명 */,
    N_IMG_RENAME VARCHAR2(300) /* 첨부파일 가명 */,
    N_SORT VARCHAR2(9) /* 구분(일반, 사업자, 공통) */,
    N_CREATEDATE DATE DEFAULT SYSDATE /* 처음 작성일 */,
    N_MODIFYDATE DATE DEFAULT SYSDATE /* 수정 작성일 */,
    N_STATUS VARCHAR2(1) DEFAULT 'Y' /* 게시글 상태 값 */
);

ALTER TABLE NOTICE ADD CONSTRAINT N_PK_NO PRIMARY KEY (N_NO);
ALTER TABLE NOTICE ADD CONSTRAINT N_CK_SORT CHECK (N_SORT IN ('일반', '사업자', '공통'));
ALTER TABLE NOTICE MODIFY N_TITLE CONSTRAINT N_NN_TITLE NOT NULL;
ALTER TABLE NOTICE MODIFY N_WRITER CONSTRAINT N_NN_WRITER NOT NULL;
ALTER TABLE NOTICE MODIFY N_CONTENT CONSTRAINT N_NN_CONTENT NOT NULL;
ALTER TABLE NOTICE MODIFY N_CREATEDATE CONSTRAINT N_NN_CREATEDATE NOT NULL;
ALTER TABLE NOTICE MODIFY N_MODIFYDATE CONSTRAINT N_NN_MODIFYDATE NOT NULL;
ALTER TABLE NOTICE MODIFY N_STATUS CONSTRAINT N_NN_STATUS NOT NULL;

COMMENT ON COLUMN NOTICE.N_NO IS '번호';
COMMENT ON COLUMN NOTICE.N_TITLE IS '제목';
COMMENT ON COLUMN NOTICE.N_WRITER IS '작성자';
COMMENT ON COLUMN NOTICE.N_CONTENT IS '내용';
COMMENT ON COLUMN NOTICE.N_IMG_ORIGIN IS '첨부파일 원명';
COMMENT ON COLUMN NOTICE.N_IMG_RENAME IS '첨부파일 가명';
COMMENT ON COLUMN NOTICE.N_SORT IS '구분(일반, 사업자, 공통)';
COMMENT ON COLUMN NOTICE.N_CREATEDATE IS '처음 작성일';
COMMENT ON COLUMN NOTICE.N_MODIFYDATE IS '수정 작성일';
COMMENT ON COLUMN NOTICE.N_STATUS IS '게시글 상태 값';


-- RESERVATION
CREATE TABLE RESERVATION(
    R_NO VARCHAR2(50),
    R_M_NO VARCHAR2(50) DEFAULT NULL,
    R_D_NO VARCHAR2(50) DEFAULT NULL,
    CAPACITY NUMBER(2,1),
    TYPE VARCHAR2(50),
    START_NAME VARCHAR2(100),
    END_NAME VARCHAR2(100),
    START_PHONE VARCHAR2(100),
    END_PHONE VARCHAR2(100),
    START_ADDR VARCHAR2(300),
    END_ADDR VARCHAR2(300),
    DISTANCE VARCHAR2(50),
    RIGHT_LOAD VARCHAR2(100),
    RIGHT_UNLOAD VARCHAR2(100),
    START_DATE DATE,
    START_TIME VARCHAR2(100),
    END_DATE DATE,
    END_TIME VARCHAR2(100),
    HELP_LOAD VARCHAR2(100),
    HELP_UNLOAD VARCHAR2(100),
    LUGGAGE VARCHAR2(4000),
    MSG VARCHAR2(2000),
    AMOUNT VARCHAR2(50),
    DEAL_YN VARCHAR2(10) DEFAULT 'N',
    DEAL_DATE DATE DEFAULT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT R_PK_NO PRIMARY KEY (R_NO);
ALTER TABLE RESERVATION ADD CONSTRAINT R_M_FK_NO FOREIGN KEY(R_M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE;
ALTER TABLE RESERVATION ADD CONSTRAINT R_D_FK_NO FOREIGN KEY(R_D_NO) REFERENCES DRIVER(D_NO) ON DELETE CASCADE;
ALTER TABLE RESERVATION MODIFY CAPACITY CONSTRAINT R_NN_CAPACITY NOT NULL;
ALTER TABLE RESERVATION MODIFY TYPE CONSTRAINT R_NN_TYPE NOT NULL;
ALTER TABLE RESERVATION MODIFY START_NAME CONSTRAINT R_NN_START_NAME NOT NULL;
ALTER TABLE RESERVATION MODIFY END_NAME CONSTRAINT R_NN_END_NAME NOT NULL;
ALTER TABLE RESERVATION MODIFY START_PHONE CONSTRAINT R_NN_START_PHONE NOT NULL;
ALTER TABLE RESERVATION MODIFY END_PHONE CONSTRAINT R_NN_END_PHONE NOT NULL;
ALTER TABLE RESERVATION MODIFY START_ADDR CONSTRAINT R_NN_START_ADDR NOT NULL;
ALTER TABLE RESERVATION MODIFY END_ADDR CONSTRAINT R_NN_END_ADDR NOT NULL;
ALTER TABLE RESERVATION MODIFY DISTANCE CONSTRAINT R_NN_DISTANCE NOT NULL;
ALTER TABLE RESERVATION MODIFY LUGGAGE CONSTRAINT R_NN_LUGGAGE NOT NULL;
ALTER TABLE RESERVATION MODIFY AMOUNT CONSTRAINT R_NN_AMOUNT NOT NULL;

COMMENT ON COLUMN RESERVATION.R_NO IS '예약번호(PK)';
COMMENT ON COLUMN RESERVATION.R_M_NO IS '멤버번호(FK)';
COMMENT ON COLUMN RESERVATION.R_D_NO IS '기사번호(FK)';
COMMENT ON COLUMN RESERVATION.CAPACITY IS '차량 크기';
COMMENT ON COLUMN RESERVATION.TYPE IS '차량 옵션';
COMMENT ON COLUMN RESERVATION.START_NAME IS '상차할 이름';
COMMENT ON COLUMN RESERVATION.END_NAME IS '하차 이름';
COMMENT ON COLUMN RESERVATION.START_PHONE IS '상차 연락처';
COMMENT ON COLUMN RESERVATION.END_PHONE IS '하차 연락처';
COMMENT ON COLUMN RESERVATION.START_ADDR IS '출발지';
COMMENT ON COLUMN RESERVATION.END_ADDR IS '도착지';
COMMENT ON COLUMN RESERVATION.DISTANCE IS '거리';
COMMENT ON COLUMN RESERVATION.RIGHT_LOAD IS '바로 상차';
COMMENT ON COLUMN RESERVATION.RIGHT_UNLOAD IS '바로 하차';
COMMENT ON COLUMN RESERVATION.START_DATE IS '상차 날짜';
COMMENT ON COLUMN RESERVATION.START_TIME IS '상차 시각';
COMMENT ON COLUMN RESERVATION.END_DATE IS '하차 날짜';
COMMENT ON COLUMN RESERVATION.END_TIME IS '하차 시각';
COMMENT ON COLUMN RESERVATION.HELP_LOAD IS '상차 도움';
COMMENT ON COLUMN RESERVATION.HELP_UNLOAD IS '하차 도움';
COMMENT ON COLUMN RESERVATION.LUGGAGE IS '이삿짐';
COMMENT ON COLUMN RESERVATION.MSG IS '전달 사항';
COMMENT ON COLUMN RESERVATION.AMOUNT IS '결제 금액';
COMMENT ON COLUMN RESERVATION.DEAL_YN IS '거래 성사 여부';
COMMENT ON COLUMN RESERVATION.DEAL_DATE IS '거래 성사 날짜';


-- PAYMENT
CREATE TABLE PAYMENT(
    P_NO VARCHAR2(50) /*결제번호(PK)*/,
    P_R_NO VARCHAR2(50) /*예약번호(FK)*/,
    CANC_YN VARCHAR2(10) DEFAULT 'N'/*취소 여부*/,
    CANC_DATE DATE DEFAULT NULL /*취소 날짜*/,
    PAY_YN VARCHAR2(10) DEFAULT 'N'/*결제 여부*/,
    ENROLL_DATE DATE DEFAULT SYSDATE /*결제 날짜*/,
    CANC_AMOUNT NUMBER /*최종 금액*/,
    CALC_YN NUMBER DEFAULT 0 /*정산여부*/
);

ALTER TABLE PAYMENT ADD CONSTRAINT P_PK_NO PRIMARY KEY (P_NO);
ALTER TABLE PAYMENT ADD CONSTRAINT P_R_FK_NO FOREIGN KEY(P_R_NO) REFERENCES RESERVATION(R_NO) ON DELETE CASCADE;
ALTER TABLE PAYMENT MODIFY PAY_YN CONSTRAINT P_NN_PAY_YN NOT NULL;
ALTER TABLE PAYMENT MODIFY ENROLL_DATE CONSTRAINT R_NN_ENROLL_DATE NOT NULL;

COMMENT ON COLUMN PAYMENT.P_NO IS '결제번호(PK)';
COMMENT ON COLUMN PAYMENT.P_R_NO IS '예약번호(FK)';
COMMENT ON COLUMN PAYMENT.CANC_YN IS '취소 여부';
COMMENT ON COLUMN PAYMENT.CANC_DATE IS '취소 날짜';
COMMENT ON COLUMN PAYMENT.PAY_YN IS '결제 여부';
COMMENT ON COLUMN PAYMENT.ENROLL_DATE IS '거래 날짜';
COMMENT ON COLUMN PAYMENT.CANC_AMOUNT IS '취소후 최종금액';
COMMENT ON COLUMN PAYMENT.CALC_YN IS '정산여부';


-- CALCULATE
CREATE TABLE CALCULATE(
    C_NO VARCHAR2(50) /*정산번호(PK)*/,
    C_P_NO VARCHAR2(50) /*결제번호(FK)*/,
    FEE VARCHAR2(50) /*용달이 수익*/,
    C_D_NO VARCHAR2(50) /*기사 번호*/,
    CHARGE VARCHAR2(50) /*기사 운임*/,
    CALC_YN VARCHAR2(10) DEFAULT 'N'/*정산 여부*/,
    CALC_DATE DATE DEFAULT SYSDATE/*정산날짜*/
);

ALTER TABLE CALCULATE ADD CONSTRAINT C_PK_NO PRIMARY KEY (C_NO);
ALTER TABLE CALCULATE ADD CONSTRAINT C_P_FK_NO FOREIGN KEY(C_P_NO) REFERENCES PAYMENT(P_NO) ON DELETE CASCADE;
ALTER TABLE CALCULATE MODIFY FEE CONSTRAINT C_NN_FEE NOT NULL;
ALTER TABLE CALCULATE MODIFY CHARGE CONSTRAINT C_NN_CHARGE NOT NULL;
ALTER TABLE CALCULATE MODIFY CALC_YN CONSTRAINT C_NN_CALC_YN NOT NULL;
ALTER TABLE CALCULATE MODIFY CALC_DATE CONSTRAINT C_NN_CALC_DATE NOT NULL;

COMMENT ON COLUMN CALCULATE.C_NO IS '정산번호(PK)';
COMMENT ON COLUMN CALCULATE.C_P_NO IS '결제번호(FK)';
COMMENT ON COLUMN CALCULATE.FEE IS '용달이수익';
COMMENT ON COLUMN CALCULATE.CHARGE IS '기사운임';
COMMENT ON COLUMN CALCULATE.C_D_NO IS '기사번호';
COMMENT ON COLUMN CALCULATE.CALC_YN IS '정산 유무';
COMMENT ON COLUMN CALCULATE.CALC_DATE IS '정산 날짜';
COMMENT ON COLUMN CALCULATE.CALC_DATE IS '정산 날짜';


-- ADDRESS
CREATE TABLE ADDRESS(
    A_NO VARCHAR2(50) /* 주소록 번호(PK) */,
    A_M_NO VARCHAR(50) /* 회원번호(FK) */,
    PLACE VARCHAR2(50) DEFAULT NULL /* 배송지명 */,
    NAME VARCHAR(50) /* 이름 */,
    ADDRESS VARCHAR2(300) /*주소*/,
    LATITUDE NUMBER /*위도*/,
    LONGITUDE NUMBER /*경도*/,
    PHONE VARCHAR2(14) /* 연락처 */,
    RECENTDATE DATE DEFAULT NULL /*최근 사용일*/
);

ALTER TABLE ADDRESS ADD CONSTRAINT A_PK_NO PRIMARY KEY (A_NO);
ALTER TABLE ADDRESS ADD CONSTRAINT A_M_FK_NO FOREIGN KEY (A_M_NO) REFERENCES MEMBER(M_NO) ON DELETE CASCADE;
ALTER TABLE ADDRESS MODIFY A_M_NO CONSTRAINT A_M_NN_NO NOT NULL;
ALTER TABLE ADDRESS MODIFY PLACE CONSTRAINT A_NN_PLACE NOT NULL;
ALTER TABLE ADDRESS MODIFY NAME CONSTRAINT A_NN_NAME NOT NULL;
ALTER TABLE ADDRESS MODIFY ADDRESS CONSTRAINT A_NN_ADDRESS NOT NULL;
ALTER TABLE ADDRESS MODIFY LATITUDE CONSTRAINT A_NN_LATITUDE NOT NULL;
ALTER TABLE ADDRESS MODIFY LONGITUDE CONSTRAINT A_NN_LONGITUDE NOT NULL;
ALTER TABLE ADDRESS MODIFY PHONE CONSTRAINT A_NN_PHONE NOT NULL;

COMMENT ON COLUMN ADDRESS.A_NO IS '주소록 번호(PK)';
COMMENT ON COLUMN ADDRESS.A_M_NO IS '회원번호(FK)';
COMMENT ON COLUMN ADDRESS.PLACE IS '배송지명';
COMMENT ON COLUMN ADDRESS.NAME IS '이름';
COMMENT ON COLUMN ADDRESS.ADDRESS IS '주소';
COMMENT ON COLUMN ADDRESS.LATITUDE IS '위도';
COMMENT ON COLUMN ADDRESS.LONGITUDE IS '경도';
COMMENT ON COLUMN ADDRESS.PHONE IS '연락처';
COMMENT ON COLUMN ADDRESS.RECENTDATE IS '최근 사용일';


-- CHATROOM
CREATE TABLE CHATROOM(
    CR_NO VARCHAR2(50) /* 방 번호(PK) */,
    SENDID VARCHAR2(50) /* 보낸사람아이디 */,
    RECEIVEID VARCHAR2(100) /* 받는사람아이디 */,
    ROOMNAME VARCHAR2(50) /* 방이름 */,
    FLAG VARCHAR2(50) /* 구분 */,
    CREATEDATE DATE DEFAULT SYSDATE /* 방생성날짜 */,
    CONNECTYN VARCHAR2(1) DEFAULT 'Y' /* 방 생성확인 */
);

ALTER TABLE CHATROOM ADD CONSTRAINT CR_PK_NO PRIMARY KEY (CR_NO);
ALTER TABLE CHATROOM MODIFY SENDID CONSTRAINT CR_NN_SENDID NOT NULL;
ALTER TABLE CHATROOM MODIFY RECEIVEID CONSTRAINT CR_NN_RECEIVEID NOT NULL;
ALTER TABLE CHATROOM MODIFY ROOMNAME CONSTRAINT CR_NN_ROOMNAME NOT NULL;
ALTER TABLE CHATROOM MODIFY FLAG CONSTRAINT CR_NN_FLAG NOT NULL;
ALTER TABLE CHATROOM MODIFY CREATEDATE CONSTRAINT CR_NN_CREATEDATE NOT NULL;
ALTER TABLE CHATROOM MODIFY CONNECTYN CONSTRAINT CR_NN_CONNECTYN NOT NULL;

COMMENT ON COLUMN CHATROOM.CR_NO IS '방 번호(PK)';
COMMENT ON COLUMN CHATROOM.SENDID IS '보낸사람 아이디';
COMMENT ON COLUMN CHATROOM.RECEIVEID IS '받는사람 아이디';
COMMENT ON COLUMN CHATROOM.ROOMNAME IS '방이름';
COMMENT ON COLUMN CHATROOM.FLAG IS '구분';
COMMENT ON COLUMN CHATROOM.CREATEDATE IS '방생성날짜';
COMMENT ON COLUMN CHATROOM.CONNECTYN IS '방생성확인';


-- CHATMESSAGE
CREATE TABLE CHATMESSAGE(
    CM_NO VARCHAR2(50) /* 메시지 번호(PK) */,
    CM_CR_NO VARCHAR2(50) /* 방 번호(FK) */,
    SENDID VARCHAR2(100) /* 보낸사람아이디 */,
    ROOMNAME VARCHAR2(50) /* 방이름 */,
    MESSAGE VARCHAR2(4000) /* 메시지 내용 */,
    SENDDATE DATE DEFAULT SYSDATE /* 메시지 보낸 날짜 */,
    FLAG VARCHAR2(50) /* 구분 */,
    CONNECTYN VARCHAR2(1) DEFAULT 'Y' /* 방 생성확인 */
);

ALTER TABLE CHATMESSAGE ADD CONSTRAINT CM_PK_NO PRIMARY KEY (CM_NO);
ALTER TABLE CHATMESSAGE ADD CONSTRAINT CM_CR_FK_NO FOREIGN KEY(CM_CR_NO) REFERENCES CHATROOM(CR_NO) ON DELETE CASCADE;
ALTER TABLE CHATMESSAGE MODIFY SENDID CONSTRAINT CM_NN_SENDID NOT NULL;
ALTER TABLE CHATMESSAGE MODIFY ROOMNAME CONSTRAINT CM_NN_ROOMNAME NOT NULL;
ALTER TABLE CHATMESSAGE MODIFY MESSAGE CONSTRAINT CM_NN_MESSAGE NOT NULL;
ALTER TABLE CHATMESSAGE MODIFY SENDDATE CONSTRAINT CM_NN_SENDDATE NOT NULL;
ALTER TABLE CHATMESSAGE MODIFY FLAG CONSTRAINT CM_NN_FLAG NOT NULL;
ALTER TABLE CHATMESSAGE MODIFY CONNECTYN CONSTRAINT CM_NN_CONNECTYN NOT NULL;

COMMENT ON COLUMN CHATMESSAGE.CM_NO IS '메시지 번호(PK)';
COMMENT ON COLUMN CHATMESSAGE.CM_CR_NO IS '방 번호(FK)';
COMMENT ON COLUMN CHATMESSAGE.SENDID IS '보낸사람 아이디';
COMMENT ON COLUMN CHATMESSAGE.ROOMNAME IS '방이름';
COMMENT ON COLUMN CHATMESSAGE.MESSAGE IS '메시지 내용';
COMMENT ON COLUMN CHATMESSAGE.SENDDATE IS '메시지 보낸 날짜';
COMMENT ON COLUMN CHATMESSAGE.FLAG IS '구분';
COMMENT ON COLUMN CHATMESSAGE.CONNECTYN IS '방생성확인';


------------------------------- 시퀀스 생성 -------------------------------------
-- Member Number
CREATE SEQUENCE SEQ_MNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- Driver Number
CREATE SEQUENCE SEQ_DNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

-- NOTICE Number
CREATE SEQUENCE SEQ_NNO
START WITH 1
INCREMENT BY 1
NOCYCLE;

/*예약 번호 시퀀스*/
CREATE SEQUENCE SEQ_RNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/* 결제 번호 시퀀스 */
CREATE SEQUENCE SEQ_PNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/* 정산 번호 시퀀스 */
CREATE SEQUENCE SEQ_CNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/* 주소록 번호 시퀀스 */
CREATE SEQUENCE SEQ_ANO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/* CHATROOM 시퀀스 */
CREATE SEQUENCE SEQ_CRNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

/* CHATMESSAGE 시퀀스 */
CREATE SEQUENCE SEQ_CMNO
START WITH 1
INCREMENT BY 1
NOCYCLE
NOCACHE;

------------------TRIGGER--------------------------------
CREATE OR REPLACE TRIGGER RESER_PAY
 AFTER INSERT ON RESERVATION
 FOR EACH ROW
 BEGIN
    INSERT INTO PAYMENT VALUES('P' || SEQ_PNO.NEXTVAL,:NEW.R_NO,DEFAULT,NULL,'Y',SYSDATE,:NEW.AMOUNT,DEFAULT);
 END;
/

CREATE OR REPLACE TRIGGER CALC_PAY
 AFTER UPDATE OF CALC_YN ON PAYMENT
 FOR EACH ROW
 BEGIN
    IF :NEW.CALC_YN=1
    THEN INSERT INTO CALCULATE VALUES('C'||SEQ_CNO.NEXTVAL,:NEW.P_NO,:NEW.CANC_AMOUNT*0.3,
                                (SELECT R_D_NO FROM RESERVATION
                                WHERE R_NO=:NEW.P_R_NO),
                                :NEW.CANC_AMOUNT*0.7,'Y',SYSDATE);
    END IF;
 END;
/

-- 수정자 : 이탐희
-- 수정일시 : 200428_17:33
-- Member 제약조건 수정(진영요청)

COMMIT;